### ISSUE TITLE
Not possible to retrieve images

### ISSUE THREAD

**Issue by lucasgiovanny** [lucasgiovanny/laravel-prestashop#2]
How the package is designed right now, is not possible to retrieve images URL from the Prestashop API.

Documentation to follow for an update:
[https://devdocs.prestashop.com/1.7/webservice/resources/images/#image_types](https://devdocs.prestashop.com/1.7/webservice/resources/images/#image_types)

**Comment by pepijndik** [comment]
https://devdocs.prestashop.com/1.7/webservice/tutorials/advanced-use/image-management/
